### ISSUE TITLE
Blacklist is now Blocklist (WP 5.5)

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/blacklist-updater#17]
With the coming WordPress 5.5 the `blacklist_keys` are changed to `blocklist_keys`.

See this changeset:
https://core.trac.wordpress.org/changeset/48121

Affected line:
https://github.com/pluginkollektiv/blacklist-updater/blob/6562e949587911cb27c53dfa8f69f02b562d1f08/inc/blacklist_updater.class.php#L128

**Comment by Zodiac1978** [comment]
The name of the option has changed in the final version of WordPress 5.5 to `disallowed_keys`
https://make.wordpress.org/core/2020/07/23/codebase-language-improvements-in-5-5/

**Comment by Zodiac1978** [comment]
If this plugin will still be maintained in the future and not added to ASB here is solution for the issue:

```
		/* Update blocklist */
		if ( false === get_option( 'disallowed_keys' ) ) {
			// WordPress before 5.5.
			update_option(
				'blacklist_keys',
				wp_remote_retrieve_body( $response )
			);
		} else {
			// WordPress 5.5 or higher.
			update_option(
				'disallowed_keys',
				wp_remote_retrieve_body( $response )
			);
		}
```

See also: 
https://github.com/pluginkollektiv/antispam-bee/issues/338
https://github.com/pluginkollektiv/antispam-bee/issues/22

**Comment by stkjj** [comment]
Regardless of the inclusion into ASB: the field in the WP backend is called "Blocklist" (already in 5.4). We can't update a blacklist, that doesn't factually exist any longer. Let's rename this plugin

**Comment by Zodiac1978** [comment]
Like I wrote in Slack: The new name is “Disallowed Comment Keys” instead of Blocklist (which was valid in 5.4).

And we can change the name but not the slug:
https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#can-i-change-my-plugins-urlslug
