### ISSUE TITLE
Test with WP 5.6

### ISSUE THREAD

**Issue by krafit** [pluginkollektiv/blacklist-updater#19]
WordPress 5.6 will be here soon. Time for us to check, if our plugins are compatible 🥳

- [x] test with the current WP 5.6 RC
- [x] add `Tested up to: 5.6` to the plugins readme
- [x] publish changes as minor update or with upcoming plugin update

**Comment by Zodiac1978** [comment]
Plugin does not work for me at the moment.

I installed the latest master and tried it on WP 5.6 RC2.

I get in my logs: `Comment block list is up to date`

Although I think this is not true as our test is just using this if the status code is *not* 200, but it don't have to be something like "304 Not Modified". 


		```if ( wp_remote_retrieve_response_code($response) !== 200 ) {
			if ( defined('WP_DEBUG_LOG') && WP_DEBUG_LOG ) {
				error_log('Comment block list is up to date');
			}

			return;
		}```

Can anyone check this too? Maybe this is just on my server on not for all?

In the browser https://raw.githubusercontent.com/splorp/wordpress-comment-blacklist/master/blacklist.txt is working, so it should be a 200 ...
