### ISSUE TITLE
Update the “Tested up to” version

### ISSUE THREAD

**Issue by splorp** [pluginkollektiv/blacklist-updater#24]
The “Tested up to” version needs to be updated, reflecting compatibility with current releases of WordPress.

I have been successfully using this plugin on two sites running WordPress 6.0.2 (and previously WP 5.7.x) without any performance or functionality issues.

This issue was also posted to the plugin support forum.

https://wordpress.org/support/topic/update-tested-up-to-version-to-6-0-2/

Thanks!

**Comment by stklcode** [comment]
Just gave it another try on a buch of test sites running 5.9, 6.0 and 6.1 nightly.

Installation, activation, deactivation and removal without issues. Cron task is registered correctly, task runs without issues and.
List is updated on first run, not modified on second run and updated again, if the previous version is manipulated in the database. Looks good to me, no reason not to raise the compatibility.

**Comment by stklcode** [comment]
done via 3f404c21c4dc110105e0c5014d81a242380ac494

Thanks for bringing this up.

**Comment by splorp** [comment]
> Thanks for bringing this up.

You’re welcome. And thanks for the quick adjustment.

Cheers!
